//=================== PROPERTY
export const GET_ALL_PROPERTY = "GET_ALL_PROPERTY";
export const GET_PROPERTIES_BY_LOCATION = "GET_PROPERTIES_BY_LOCATION";
export const GET_FEATURED_PROPERTIES = "GET_FEATURED_PROPERTIES";
export const GET_AFFORDABLE_PROPERTIES = "GET_AFFORDABLE_PROPERTIES";
export const SET_HISTORY_SEARCH = "SET_HISTORY_SEARCH";
export const GET_PROPERTY = "GET_PROPERTY";
export const GET_SIMILAR_PROPERTIES = "GET_SIMILAR_PROPERTIES";
export const GET_ALL_APARTMENT = "GET_ALL_APARTMENT";
export const GET_USER_PROPERTY_LIST = "GET_USER_PROPERTY_LIST";
export const CLEAR_PROPERTY_LIST = "CLEAR_PROPERTY_LIST";
export const SAVE_PROPERTY = "SAVE_PROPERTY";
export const DELETE_PROPERTY_FROM_LIST = "DELETE_PROPERTY_FROM_LIST";
export const SORT_BY = "SORT_BY";
export const POST_PROPERTY = "POST_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
//=================== AUTH
export const USER_LOADED = "USER_LOADE";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN = "LOGIN";
export const DELETE_USER = "DELETE_USER";
export const LOGOUT = "LOGOUT";
//=================== ERROR
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ERROR = "ERROR";
//=================== FORMS
export const SHOW_SIGNUP = "SHOW_SIGNUP";
export const SHOW_SIGNIN = "SHOW_SIGNIN";
export const CLOSE_FORMS = "CLOSE_FORMS";
