//=================== PROPERTY
export const GET_PROPERTIES_BY_LOCATION = 'GET_PROPERTIES_BY_LOCATION';
export const GET_CITIES_BY_CURRENT_LOCATION = 'GET_CITIES_BY_CURRENT_LOCATION';
export const GET_SIMILAR_PROPERTIES = 'GET_SIMILAR_PROPERTIES';
export const GET_FEATURED_PROPERTIES = 'GET_FEATURED_PROPERTIES';
export const SET_STATE_SEARCH = 'SET_STATE_SEARCH';
export const SET_HISTORY_SEARCH = 'SET_HISTORY_SEARCH';
export const GET_PROPERTY = 'GET_PROPERTY';
export const POST_PROPERTY = 'POST_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
//=================== AUTH
//=================== ERROR
export const ERROR = 'ERROR';
